site_name: Libro Digital de Programación
site_description: Cuadernos de programación convertidos a libro digital estático con MkDocs.
site_author: UPeU
copyright: Angel Sullon @asullom

theme:
  name: material
  language: es
  palette:
        - scheme: default
          primary: teal
          accent: amber
  features:
        - navigation.sections
        - navigation.expand
        - navigation.top
        - toc.follow
        - content.code.copy
        - search.suggest
        - search.highlight

plugins:
  - search
  - mkdocs-jupyter:
          execute: false
          include_source: true
          ignore_h1_titles: true

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
          permalink: true
  - pymdownx.details
  - pymdownx.tabbed:
          alternate_style: true
  - pymdownx.superfences

nav:
    - Inicio: index.md
    - Sílabo: Silabo_FP.md
    - Guía de apoyo: Guia_algoritmo_a_codigo.ipynb
    - Capítulo 1. Resolución de problemas básicos:
            - Sesión 1: Sesion_01_Pensamiento_Algoritmico_Variables_Tipos_Datos.ipynb
            - Sesión 2: Sesion_02_Operadores_Expresiones_Secuencia.ipynb
            - Sesión 3: Sesion_03_Decisiones_Simples_Compuestas.ipynb
            - Sesión 4: Sesion_04_Decisiones_Multiples_Casos_Limite.ipynb
            - Sesión 5: Sesion_05_Evaluacion_1.ipynb
    - Capítulo 2. Resolución de problemas iterativos y procesamiento de datos:
            - Sesión 6: Sesion_06_Repeticion_Definida_For.ipynb
            - Sesión 7: Sesion_07_Repeticion_Condicionada_While.ipynb
            - Sesión 8: Sesion_08_Listas_Cadenas_Procesamiento_Colecciones.ipynb
            - Sesión 9: Sesion_09_Busqueda_Secuencial_Ordenacion_Basica.ipynb
            - Sesión 10: Sesion_10_Matrices_Organizacion_Tabular.ipynb
            - Sesión 11: Sesion_11_Diccionarios_Consulta_Datos.ipynb
            - Sesión 12: Sesion_12_Evaluacion_2.ipynb
    - Capítulo 3. Resolución de problemas estructurados y persistencia básica:
            - Sesión 13: Sesion_13_Funciones_Parametros_Retorno_Modularizacion.ipynb
            - Sesión 14: Sesion_14_Integracion_Funciones_Colecciones_Menus.ipynb
            - Sesión 15: Sesion_15_Persistencia_Basica_Archivos.ipynb
            - Sesión 16: Sesion_16_Evaluacion_Final.ipynb
